### ISSUE TITLE
Potential bug when partially training a Gaussian Naive Bayes model

### ISSUE THREAD

**Issue by cioroianudenis** [RubixML/ML#83] opened 2020-06-25 17:25 UTC
So I have the following code:

```php
$estimator = new PersistentModel(
    new Pipeline([
        new TextNormalizer(),
        new StopWordFilter(StopWords::$words),
        new WordCountVectorizer(10000, 1, new NGram(1, 2, new WordStemmer('romanian'))),
        new TfIdfTransformer(),
        new ZScaleStandardizer(),
    ], new GaussianNB()),
    new Filesystem($this->path.'/categorization.model', true)
);

$categories = Category::has('variants')->with('variants')->get();

$samples = [];
$labels = [];
foreach ($categories as $category) {
    foreach ($category->variants as $variant) {
        $samples[] = [$variant->title];
        $labels[] = $category->slug;
    }
}

$foldsNo = 10;
$dataset = new Labeled($samples, $labels);
$folds = $dataset->fold($foldsNo);

$estimator->train($folds[0]);
for($i = 1; $i < $foldsNo; $i++) {
    $estimator->partial($folds[$i]);
}

$estimator->save();

```
which tries to train a `GaussianNB` model on 26 thousand products and their associated labels, but for some reason I get the following error:
```

ErrorException
Undefined offset: 0
```
in `rubix\ml\src\Classifiers\GaussianNB.php:267` which corresponds to the following code: `$means[$column] = (($n * $mean) + ($oldWeight * $oldMeans[$column])) / ($oldWeight + $n);` , the problem seems to be here `$oldMeans[$column]` when trying to access a property which doesn't exist, but I have no idea why that property doesn't exist.

I don't suspect that the training data has any errors since if I fully train the same model with `$estimator->train($dataset)` works as expected (Batch learning in one single session).

When I tried to debug the code I have the following:

I see that lines 256, 257 and 259 have this code:

```php
$means = $oldMeans = $this->means[$class] ?? [];
$variances = $oldVariances = $this->variances[$class] ?? [];

$oldWeight = $this->weights[$class] ?? 0;

```
which assigns `[]` empty array if `$this->means[$class] `, `$this->variances[$class]` and `$this->weights[$class]` don't exist, but if `$oldMeans`  is empty array I think `$oldMeans[$column]` would throw out that error. So a fix would be to put `($oldMeans[$column] ?? 0)` in `rubix\ml\src\Classifiers\GaussianNB.php:267` instead of `$oldMeans[$column]` I think. I am not 100% how that would affect the training of the model tho.

I hope that I am not mistaken.

Thank you!

**Comment by andrewdalpino** [comment] 2020-06-26 05:13
Hey @cioroianudenis when doing online training, the first training set will determine the classes that the learner learns. Looks like I tried to adapt to new class labels but that's not working properly. If the first fold does not contain all the class labels, you may run into this problem. Instead of `fold()` try `stratifiedFold()` on the [Labeled](https://docs.rubixml.com/en/latest/datasets/labeled.html#stratification) dataset object to ensure that each fold contains all the class labels.

**Example**

```php
foreach ($dataset->stratifiedFold(10) as $fold) {
    $estimator->partial($fold);
}
```

Let me know if that fixes the issue and we'll go from there

(Bear in mind that folding in this way offers no benefit over batch learning as you're just breaking a dataset that's already in memory into multiple smaller ones and still training on all of them in the same session. In fact, you pay the penalty of having to recompute means and variances this way.)

**Comment by andrewdalpino** [comment] 2020-06-26 05:53
Should be fixed in this commit https://github.com/RubixML/RubixML/commit/3d868cfb38eabc5cdeea7768c95e66c0690ae515

You can install the latest `dev-master` to test

Could you please also test `stratifiedFold()` just to confirm that indeed unseen class labels was the issue?

Thanks for the great bug report! Feel free to join our channel on Telegram https://t.me/RubixML

**Comment by cioroianudenis** [comment] 2020-06-26 16:49
Hello @andrewdalpino, the `stratifiedFold()` indeed works as intended.
Didn't get the chance to test the new fix, once I test it, I'll come back and post the results.
Thank you for telegram invitation, I will most certainly join, I'm happy to help.

**Comment by andrewdalpino** [comment] 2020-06-27 02:44
Thank you @cioroianudenis let me know if the new `dev-master` works even without using stratified folds

See you in the channel!

**Comment by cioroianudenis** [comment] 2020-06-27 12:31
@andrewdalpino I have managed to test it, it doesn't give the same error anymore, but now it runs out of memory (i gave it 8GB of ram), just like what happend when I tried to test `stratifiedFold()` or full train (with still 8GB of ram), which is to be expected since it is alot of data for the memory to manage.
I tested the following code

```php
$categories = Category::has('variants')->with('variants')->get();

$samples = [];
$labels = [];
foreach ($categories as $category) {
    foreach ($category->variants as $variant) {
        $samples[] = [$variant->title];
        $labels[] = $category->slug;
    }
}

$foldsNo = 10;
$dataset = new Labeled($samples, $labels);
$folds = $dataset->fold($foldsNo);

for($i = 0; $i < $foldsNo; $i++) {
    $estimator->partial($folds[$i]);
}

$estimator->save();
```
after it ran out of memory, I tried another approach to partially train the model which worked, it didn't give any errors or run out of memory but the resulting trained model has only 6 MB of data, which leads me to believe that it didn't train on the whole data, the reason I think this is I have another model that was trained on 14.000 products with batch training(in a single run) and had 43 MB of data.
This time I have 26.000 products and the model only has 6 MB with partial training on all of them.

This is the other alternative which worked but gave the 6 MB model:

```php
$start = 1;
$limit = 2;
$categories = Category::has('variants')->with('variants')->skip($start)->limit($limit)->get();

while($categories->count()) {
    $samples = [];
    $labels = [];

    foreach ($categories as $category) {
        foreach ($category->variants as $variant) {
            $samples[] = [$variant->title];
            $labels[] = $category->slug;
        }
    }

    $dataset = new Labeled($samples, $labels);
    $estimator->partial($dataset);

    $start += $limit;
    $categories = Category::has('variants')->with('variants')->skip($start)->limit($limit)->get();
}

$estimator->save();
```
Basically all it does is loading from the database only 2 categories at a time which have a maximum of 1000 products associated with them, and I create a new `$dataset` in a while loop and I feed it to the estimator with `partial($dataset)`.

I also tested some predictions on the 6 MB model vs the 43 MB model, and the 43 MB was returning correct every time, while the 6 MB one wasn't.

I hope my explanation is clear enough.
Thank you!

Edit 1:
I made it kinda work with folding by increasing the number of folds, I first gave it `$folds = $dataset->fold(10);` which resulted in 8 GB out of memory.
I then gave it `$folds = $dataset->fold(20);` which worked and compiled a 27 MB of data model but used around 6.5 GB of ram - the predictions weren't good for some tests that I made.
After that I gave it `$folds = $dataset->fold(60);` which was half the number of `$categories` fetched form the database and I saw it using around 2.5 GB of ram at maximum but compiled a 9.3 MB data model that again still predicted wrong on testing products.

**Comment by andrewdalpino** [comment] 2020-06-27 18:44
@cioroianudenis It's likely that the vocabulary built by [Word Count Vecotorizer](https://docs.rubixml.com/en/latest/transformers/word-count-vectorizer.html) is not suitable as it's being fitted with less data now.

```php
echo count(current($transformer->vocabulary()));
```

will give you the size of the vocabulary of the first feature column. If it's set to 10,000 and your vocab contains alot less or has junk features, this may explain the issue. Instead you can fit Word Count Vectorizer on the full dataset or a larger portion at least and THEN inject it into the Pipeline.

```php
use Rubix\ML\Transformers\WordCountVectorizer;
use Rubix\ML\Other\Tokenizers\NGram;
use Rubix\ML\Other\Tokenizers\WordStemmer;

$transformer = new WordCountVectorizer(10000, 1, new NGram(1, 2, new WordStemmer('romanian')));

$transformer->fit($dataset); // Fitted with a dataset large enough to build a good vocabulary

$estimator = new PersistentModel(
    new Pipeline([
        new TextNormalizer(),
        new StopWordFilter(StopWords::$words),
        $transformer,
        new TfIdfTransformer(),
        new ZScaleStandardizer(),
    ], new GaussianNB()),
    new Filesystem($this->path.'/categorization.model', true)
);
```

Calling `partial()` on Pipeline will not refit WordCountVectorizer so you can use it with the custom fittings but as soon as you call `train()` Pipeline will refit it just a heads up. Note that you'll probably want to normalize and stop word filter before fitting WordCountVectorizer.

**Comment by cioroianudenis** [comment] 2020-06-27 19:29
@andrewdalpino I tried it like this, but now it uses so much ram, 8 GB is not enough, it gives out of memory error.

**Comment by andrewdalpino** [comment] 2020-06-27 19:35
Ok, you can either try filtering your dataset so that it fits into memory or getting more RAM

Were you able to confirm that indeed a poor vocabulary was the issue?

**Comment by cioroianudenis** [comment] 2020-06-27 19:45
@andrewdalpino not quite, I can't compute the model on all the products, even with using the new solution. Probably that would be the case for it not predicting like the one trained in batch mode that has 14k products, but I can't test it. 
Thing is, if this chugs on 26k products, then my dream of training for on 1-2 million products goes straight to the trash on a normal laptop hahaha, I'll see what I can do to minimize the product count and make it work.

**Comment by andrewdalpino** [comment] 2020-06-27 19:49
Sounds good @cioroianudenis 

The issue is that Word Count Vectorizer needs to build a vocabulary somehow and it does so using all the words contained in the dataset used to fit it. This cannot be done partially (Word Count Vectorizer does not implement the [Elastic](https://docs.rubixml.com/en/latest/transformers/api.html#elastic) interface for this reason). Having that said, you do not need to build a vocabulary from *all* your training samples, you only need *enough* and once fitted you can train on as many samples as you like as Gaussian NB tends to scale well and can be partially trained.

**Comment by cioroianudenis** [comment] 2020-06-27 20:52
@andrewdalpino yeah that's what I was thinking.
I tested it again, I built the word count vectorizer on only 1k products, and tried training the model on all the training samples (26k items), but I still get out of memory when the model begins to train.
I think there still is a memory leak somewhere when calling `partial()`.

**Comment by andrewdalpino** [comment] 2020-06-27 20:56
Are you using dev-master or another version?

**Comment by cioroianudenis** [comment] 2020-06-27 20:59
@andrewdalpino i'm using the branch `master` from https://github.com/RubixML/RubixML, cloned it on local.

**Comment by andrewdalpino** [comment] 2020-06-27 21:06
Ok you can also try limiting your vocabulary to a size that is a power of 2 (or slightly less if you have other features) to reduce the amount of wasted memory since that's how PHP allocates memory under the hood

I'll profile GaussianNB asap

**Comment by cioroianudenis** [comment] 2020-06-27 21:06
@andrewdalpino nvm, I think it's a problem of fine tuning, went with 3000 words in tokenzier, and it works. Kinda getting the hang of it.

**Closed as completed** 2020-06-29 12:25 UTC
Labels: bug
